import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create((theme) => ({
  topSection: {
    marginBottom: theme.metrics.spacingV.p16,
  },
  currentLabel: {
    fontSize: theme.fonts.size.xxs,
    opacity: 0.6,
  },
  nameTimeRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginTop: theme.metrics.spacingV.p4,
  },
  prayerTime: {
    fontVariant: ['tabular-nums'],
  },
  timerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.metrics.spacing.p4,
    marginTop: theme.metrics.spacingV.p4,
  },
  timerText: {},
  timelineContainer: {
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  timelineLine: {
    position: 'absolute',
    top: 12,
    left: 0,
    right: 0,
    height: 1,
    opacity: 0.5,
    backgroundColor: theme.colors.border.default,
  },
  timelineItemPressable: {
    paddingVertical: theme.metrics.spacingV.p4,
    paddingHorizontal: theme.metrics.spacing.p4,
  },
  timelineItem: {
    alignItems: 'center',
    gap: 6,
    zIndex: 1,
  },
  dotCompleted: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    backgroundColor: theme.colors.state.successBg,
    borderColor: theme.colors.state.success,
  },
  dotCurrent: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
    backgroundColor: theme.colors.brand.primary,
    shadowColor: theme.colors.brand.primary,
  },
  dotCurrentInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.text.inverse,
  },
  dotUpcoming: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.colors.background.surface,
    borderColor: theme.colors.border.default,
  },
  dotUpcomingInner: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.colors.icon.muted,
  },
  dotSelectedRing: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: theme.colors.brand.primary,
  },
  prayerLabel: {
    fontSize: theme.fonts.size.xxs,
  },
  labelCompleted: {
    opacity: 0.4,
    color: theme.colors.brand.secondary,
  },
  labelCurrent: {
    color: theme.colors.brand.primary,
  },
  labelUpcoming: {
    color: theme.colors.brand.secondary,
    opacity: 0.5,
  },
  labelSelected: {
    opacity: 1,
    color: theme.colors.brand.primary,
  },
  staleBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: theme.metrics.spacingV.p8,
    paddingTop: theme.metrics.spacingV.p8,
    borderTopWidth: 1,
    borderTopColor: theme.colors.border.default,
    opacity: 0.7,
  },
}));
